RAW_ENABLE = yes
CONSOLE_ENABLE = yes
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes

EEPROM_DRIVER = wear_leveling
WEAR_LEVELING_DRIVER = rp2040_flash
OPT_DEFS += -DWEAR_LEVELING_LOGICAL_SIZE=32768
OPT_DEFS += -DWEAR_LEVELING_BACKING_SIZE=65536

SRC += jpad_config.c jpad_protocol.c
